"""empty message

Revision ID: 14dc461f379f
Revises: 
Create Date: 2026-06-13 20:55:07.347629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dc461f379f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('super_last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_operations', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('balance >= 0', name='balance_check'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_account_user_id', 'account', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('super_last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('idx_contact_user_id', 'contact', ['user_id'], unique=False)
    op.create_table('card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('card_holder_name', sa.String(length=100), nullable=True),
    sa.Column('valid_through_date', sa.String(length=5), nullable=True),
    sa.Column('cvv2_cvc2_number', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['phone_number'], ['user.phone_number'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_index('idx_card_account_id', 'card', ['account_id'], unique=False)
    op.create_index('idx_card_phone_number', 'card', ['phone_number'], unique=False)
    op.create_table('transaction',
    sa.Column('txn_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('txn_type', sa.Enum('C', 'D', name='txntype'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('txn_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index('idx_txn_account_id', 'transaction', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_txn_account_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('idx_card_phone_number', table_name='card')
    op.drop_index('idx_card_account_id', table_name='card')
    op.drop_table('card')
    op.drop_index('idx_contact_user_id', table_name='contact')
    op.drop_table('contact')
    op.drop_index('idx_account_user_id', table_name='account')
    op.drop_table('account')
    op.drop_table('user')
    # ### end Alembic commands ###
